Using Linear Regression

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd 
import tensorflow as tf 

In [2]:
x_train = np.array([[1.0],[2.0]], dtype=np.float32)
y_train = np.array([[300.0],[500.0]],dtype=np.float32) 

In [4]:
linear_layer = tf.keras.layers.Dense(units=1, activation='linear')

In [ ]:
#Input to the layer must be 2-D, so we'll reshape it
a1 = linear_layer(x_train[0].reshape(1,1))

In [7]:
print(a1)

tf.Tensor([[-0.23948848]], shape=(1, 1), dtype=float32)


In [ ]:
#Wieghts are randomly initialized to small numbers and the bias default to beign initialized to zero
w, b = linear_layer.get_weights()
print("w:",w," b:",b)

w: [[-0.23948848]]  b: [0.]


In [ ]:
#The weights are initialized to random values so let's set them to some known values
set_w = np.array([[200]])
set_b = np.array([100])

#Set weights takes a list of numpy arrays
linear_layer.set_weights([set_w, set_b])
print(linear_layer.get_weights())

[array([[200.]], dtype=float32), array([100.], dtype=float32)]


In [ ]:
#Let's compare euqation (1) to the layer output
a1 = linear_layer(x_train[0].reshape(1,1))
print(a1)
alin = np.dot(set_w, x_train[0].reshape(1,1)) + set_b
print(alin)

tf.Tensor([[300.]], shape=(1, 1), dtype=float32)
[[300.]]


In [ ]:
#Use our linear layer to make predictions on our training data
prediction_tf = linear_layer(x_train)
prediction_np = np.dot(x_train, set_w) + set_b


In [16]:
print(prediction_tf)
print(prediction_np)

tf.Tensor(
[[300.]
 [500.]], shape=(2, 1), dtype=float32)
[[300.]
 [500.]]


Using Logistic Regression

In [18]:
#data set
x_train = np.array([0.,1,2,3,4],dtype=np.float32).reshape(-1,1) #2-D Matrix
y_train = np.array([0,0,0,1,1,1], dtype=np.float32).reshape(-1,1) # 2-D matrix 

In [19]:
from tensorflow.keras import Sequential
from tensorflow.keras.losses import MeanSquaredError, BinaryCrossentropy
from tensorflow.keras.activations import sigmoid

In [ ]:
#logistic neuron
model = Sequential(
    [
        tf.keras.layers.Dense(1, input_dim=1, activation='sigmoid', name='L1')
    ]
)

C:\Users\SUYASH\AppData\Roaming\Python\Python311\site-packages\keras\src\layers\core\dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [21]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ L1 (Dense)                      │ (None, 1)              │             2 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 2 (8.00 B)

 Trainable params: 2 (8.00 B)

 Non-trainable params: 0 (0.00 B)

In [ ]:
#Initializing random weights to L1
logistic_layer = model.get_layer('L1')
w,b = logistic_layer.get_weights()
print(w,b)
print(w.shape, b.shape)

[[1.1508545]] [0.]
(1, 1) (1,)


In [24]:
#Setting some know weights and bias
set_w = np.array([[2]])
set_b = np.array([-4.5])

logistic_layer.set_weights([set_w, set_b])
print(logistic_layer.get_weights())

[array([[2.]], dtype=float32), array([-4.5], dtype=float32)]


In [ ]:
#Comparing equation 2 to the layer output
a1 = model.predict(x_train[0].reshape(1,1))
print(a1)
alog = sigmoid(np.dot(set_w, x_train[0].reshape(1,1)) + set_b)
print(alog)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 69ms/step
[[0.01098694]]
tf.Tensor([[0.01098694]], shape=(1, 1), dtype=float64)
