In [15]:
#create model class
import torch
import torch.nn as nn

class MySimpleNN(nn.Module):
    def __init__(self, num_features):
        super().__init__()
        self.linear1 = nn.Linear(num_features, 3)
        self.relu = nn.ReLU()
        self.linear2 = nn.Linear(3,1)
        self.sigmoid = nn.Sigmoid()
        
    def forward(self, features):
        out = self.linear1(features)
        out = self.relu(out)
        out = self.linear2(out)
        out = self.sigmoid(out)
        return out
    

In [16]:
#create dataset
features = torch.rand(10,5)

#create model
model = MySimpleNN(features.shape[1])

#call model for forward pass
model(features)

tensor([[0.4631],
        [0.4202],
        [0.4092],
        [0.4549],
        [0.4109],
        [0.4349],
        [0.4710],
        [0.4211],
        [0.4212],
        [0.4100]], grad_fn=<SigmoidBackward0>)

In [17]:
#show model weights
model.linear1.weight

Parameter containing:
tensor([[ 0.0500, -0.0316, -0.2979, -0.0314, -0.2922],
        [-0.2613,  0.2758,  0.3347,  0.2361,  0.0312],
        [-0.4256, -0.3245,  0.0582,  0.4307,  0.1141]], requires_grad=True)

In [18]:
from torchinfo import summary
summary(model, input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
MySimpleNN                               [10, 1]                   --
├─Linear: 1-1                            [10, 3]                   18
├─ReLU: 1-2                              [10, 3]                   --
├─Linear: 1-3                            [10, 1]                   4
├─Sigmoid: 1-4                           [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

In [19]:
class MySimpleNN1(nn.Module):
    def __init__(self, num_features):
        
        super().__init__()
        self.network = nn.Sequential(
            nn.Linear(num_features, 3),
            nn.ReLU(),
            nn.Linear(3, 1),
            nn.Sigmoid()
        )
        
    def forward(self, features):
        out = self.network(features)
        return out

In [20]:
#create dataset
features = torch.rand(10,5)

#create model
model1 = MySimpleNN1(features.shape[1])

#call model for forward pass
model(features)

tensor([[0.4447],
        [0.4851],
        [0.4088],
        [0.4373],
        [0.4376],
        [0.4098],
        [0.4122],
        [0.4321],
        [0.4545],
        [0.4234]], grad_fn=<SigmoidBackward0>)

In [22]:
from torchinfo import summary
summary(model1, input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
MySimpleNN1                              [10, 1]                   --
├─Sequential: 1-1                        [10, 1]                   --
│    └─Linear: 2-1                       [10, 3]                   18
│    └─ReLU: 2-2                         [10, 3]                   --
│    └─Linear: 2-3                       [10, 1]                   4
│    └─Sigmoid: 2-4                      [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00